"""Update tabel staff

Revision ID: 1f46a0625278
Revises: 21614a73e31c
Create Date: 2025-12-14 11:36:22.808236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f46a0625278'
down_revision = '21614a73e31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('status_note', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('staff', 'status')
    op.drop_column('staff', 'attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('attendance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_table('attendance_logs')
    # ### end Alembic commands ###
