"""Menambahkan tabel staff

Revision ID: 21614a73e31c
Revises: 36cc78772a84
Create Date: 2025-12-14 11:29:44.989104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21614a73e31c'
down_revision = '36cc78772a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('master_ingredients', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(op.f('fk_user_ingredient'), 'master_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'master_ingredients', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_menu'), 'menu_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'menu_ingredients', 'menus', ['menu_id'], ['id'])
    op.alter_column('menus', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('menus', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_constraint(op.f('fk_user_menu'), 'menus', type_='foreignkey')
    op.create_foreign_key(None, 'menus', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_menu'), 'menus', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('menus', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('menus', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'menu_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_menu'), 'menu_ingredients', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'master_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_ingredient'), 'master_ingredients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('master_ingredients', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('staff')
    # ### end Alembic commands ###
