"""Update tabel users untuk role sekolah dan lansia

Revision ID: 2a9dc73021e7
Revises: cb9f93adef50
Create Date: 2026-01-04 14:14:19.367257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a9dc73021e7'
down_revision = 'cb9f93adef50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nisn', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('npsn', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('sekolah_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('file_sk_operator', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['sekolah_id'], ['id'])
    op.drop_column('users', 'regency')
    op.drop_column('users', 'district')
    op.drop_column('users', 'province')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('province', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('district', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('regency', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'file_sk_operator')
    op.drop_column('users', 'sekolah_id')
    op.drop_column('users', 'npsn')
    op.drop_column('users', 'nisn')
    # ### end Alembic commands ###
