"""tambah penerima manfaat

Revision ID: 38d7ba4c66c7
Revises: 1f46a0625278
Create Date: 2025-12-14 18:59:50.769689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d7ba4c66c7'
down_revision = '1f46a0625278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('nama_lokasi', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=200), nullable=True),
    sa.Column('kuota', sa.Integer(), nullable=True),
    sa.Column('pic_nama', sa.String(length=100), nullable=True),
    sa.Column('pic_telepon', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penerima')
    # ### end Alembic commands ###
