"""menambah kolom temp_otp 

Revision ID: 46537861bdc1
Revises: c16f69e9fa0d
Create Date: 2026-01-06 20:52:00.623438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46537861bdc1'
down_revision = 'c16f69e9fa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_created_at')
    # ### end Alembic commands ###
