"""tambah kolom school_token

Revision ID: 4659ee8eb703
Revises: 80e6b011ea53
Create Date: 2026-01-13 14:44:50.833081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4659ee8eb703'
down_revision = '80e6b011ea53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menus', 'distribution_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('users', sa.Column('school_token', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'users', ['school_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'school_token')
    op.alter_column('menus', 'distribution_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
