"""Update Standar MBG 2025 columns

Revision ID: 633f8985fd32
Revises: 9fef9042dc0a
Create Date: 2025-12-23 12:11:23.266504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633f8985fd32'
down_revision = '9fef9042dc0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_ingredients', sa.Column('fiber', sa.Float(), nullable=True))
    op.add_column('master_ingredients', sa.Column('calcium', sa.Float(), nullable=True))
    op.add_column('master_ingredients', sa.Column('iron', sa.Float(), nullable=True))
    op.add_column('master_ingredients', sa.Column('vit_a', sa.Float(), nullable=True))
    op.add_column('master_ingredients', sa.Column('vit_c', sa.Float(), nullable=True))
    op.add_column('master_ingredients', sa.Column('folate', sa.Float(), nullable=True))
    op.add_column('master_ingredients', sa.Column('vit_b12', sa.Float(), nullable=True))
    op.add_column('menus', sa.Column('total_fiber', sa.Float(), nullable=True))
    op.add_column('menus', sa.Column('total_calcium', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'total_calcium')
    op.drop_column('menus', 'total_fiber')
    op.drop_column('master_ingredients', 'vit_b12')
    op.drop_column('master_ingredients', 'folate')
    op.drop_column('master_ingredients', 'vit_c')
    op.drop_column('master_ingredients', 'vit_a')
    op.drop_column('master_ingredients', 'iron')
    op.drop_column('master_ingredients', 'calcium')
    op.drop_column('master_ingredients', 'fiber')
    # ### end Alembic commands ###
