"""Update Table Naame

Revision ID: 6554cc2baa7f
Revises: f6527b535ff8
Create Date: 2026-01-04 22:38:04.906731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6554cc2baa7f'
down_revision = 'f6527b535ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.drop_column('users', 'whatsapp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
