"""tambah kolom

Revision ID: 6c968062f1db
Revises: 88db7a1813e8
Create Date: 2026-01-15 06:09:34.860487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c968062f1db'
down_revision = '88db7a1813e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ulasan_penerima', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('ulasan_penerima', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('ulasan_penerima', sa.Column('status_ai', sa.String(length=20), nullable=True))
    op.alter_column('ulasan_penerima', 'ulasan_teks',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ulasan_penerima', 'ulasan_teks',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('ulasan_penerima', 'status_ai')
    op.drop_column('ulasan_penerima', 'tags')
    op.drop_column('ulasan_penerima', 'rating')
    # ### end Alembic commands ###
