"""Update DB menu

Revision ID: 80e6b011ea53
Revises: 46537861bdc1
Create Date: 2026-01-11 19:45:55.338738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e6b011ea53'
down_revision = '46537861bdc1'
branch_labels = None
depends_on = None


def upgrade():
    # op.add_column('menus', sa.Column('total_vit_a', sa.Float(), nullable=True))
    # op.add_column('menus', sa.Column('total_fiber', sa.Float(), nullable=True))
    # op.add_column('menus', sa.Column('total_fat', sa.Float(), nullable=True))
    # op.add_column('menus', sa.Column('total_carb', sa.Float(), nullable=True))
    # op.add_column('menus', sa.Column('distribution_date', sa.Date(), nullable=True))
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'total_vit_a')
    op.drop_column('menus', 'total_iron')
    op.drop_column('menus', 'distribution_date')
    op.drop_column('master_ingredients', 'weight')
    # ### end Alembic commands ###
