"""Update Tabel 2

Revision ID: 88db7a1813e8
Revises: a35991b6f89a
Create Date: 2026-01-15 03:32:04.975647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88db7a1813e8'
down_revision = 'a35991b6f89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('konten', sa.Text(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('target_role', sa.String(length=20), nullable=True),
    sa.Column('dapur_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dapur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artikel')
    # ### end Alembic commands ###
