"""tambah proses memasak

Revision ID: 9fef9042dc0a
Revises: 38d7ba4c66c7
Create Date: 2025-12-14 20:38:15.614054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fef9042dc0a'
down_revision = '38d7ba4c66c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aktivitas_dapur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jenis_aktivitas', sa.String(length=50), nullable=False),
    sa.Column('bukti_foto', sa.String(length=255), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=True),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aktivitas_dapur')
    # ### end Alembic commands ###
