"""Update db Class

Revision ID: adfb95a564f0
Revises: 4659ee8eb703
Create Date: 2026-01-14 19:45:55.156659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfb95a564f0'
down_revision = '4659ee8eb703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_class', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_class')
    # ### end Alembic commands ###
