"""Update nama sekolah

Revision ID: b90ef4965b3d
Revises: 2a9dc73021e7
Create Date: 2026-01-04 14:30:59.492929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90ef4965b3d'
down_revision = '2a9dc73021e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('student_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_count')
    op.drop_column('users', 'school_name')
    # ### end Alembic commands ###
