"""menambah kolom temp_otp untuk verifikasi email

Revision ID: c16f69e9fa0d
Revises: 6554cc2baa7f
Create Date: 2026-01-06 20:50:57.400196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16f69e9fa0d'
down_revision = '6554cc2baa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_otp', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_otp')
    # ### end Alembic commands ###
