"""menambah tabel ulasan penerima

Revision ID: cb9f93adef50
Revises: 633f8985fd32
Create Date: 2025-12-24 09:43:22.265970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9f93adef50'
down_revision = '633f8985fd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ulasan_penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_pengulas', sa.String(length=100), nullable=True),
    sa.Column('ulasan_teks', sa.Text(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ulasan_penerima')
    # ### end Alembic commands ###
