"""Update Laporan Kendala

Revision ID: d5c410979861
Revises: f27636b689e8
Create Date: 2026-01-22 19:30:45.034558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c410979861'
down_revision = 'f27636b689e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laporan_kendala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dapur_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('foto_bukti', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dapur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan_kendala')
    # ### end Alembic commands ###
