"""Update user

Revision ID: f6527b535ff8
Revises: b90ef4965b3d
Create Date: 2026-01-04 18:11:56.115058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6527b535ff8'
down_revision = 'b90ef4965b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('province', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('village', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('dapur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['dapur_id'], ['id'])
    op.drop_column('users', 'file_slhs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('file_slhs', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'dapur_id')
    op.drop_column('users', 'village')
    op.drop_column('users', 'district')
    op.drop_column('users', 'city')
    op.drop_column('users', 'province')
    # ### end Alembic commands ###
